name: mChat
main: net.D3GN.MiracleM4n.mChat.mChat
version: 1.8.3_2
author: MiracleM4n
website: http://d3gn.net/
thread: http://forums.bukkit.org/threads/22958/
softdepend: [Permissions, GroupManager, PermissionsBukkit, bPermissions, Spout, PermissionsEx]
description: Chat API with more.
commands:
    mchat:
        description:
        permissions:
        usage: |
            /<command> reload [config/info/censor/all]
            Example: /<command> - See this info.
            Example: /<command> reload config - Reload Config.
            Example: /<command> reload info - Reload Info.
            Example: /<command> reload censor - Reload Info.
            Example: /<command> reload all - Reload All Configs.

permissions:
    mchat.reload:
        description: Allow usage of /mchat reload '[config/info/censor/all]'
        default: true